app/home/__init__.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# @Time    : 2019/1/22 11:59
# @User    : zhunishengrikuaile
# @File    : __init__.py
# @Email   : binary@shujian.org
# @MyBlog  : WWW.SHUJIAN.ORG
# @NetName : 書劍
# @Software: TheMovie
from flask import Blueprint

home = Blueprint("home", __name__)

import app.home.views

app/home/views.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# @Time    : 2019/1/22 12:00
# @User    : zhunishengrikuaile
# @File    : views.py
# @Email   : binary@shujian.org
# @MyBlog  : WWW.SHUJIAN.ORG
# @NetName : 書劍
# @Software: TheMovie

from app.home import home
from flask import render_template  # 导入页面渲染函数
from flask import redirect  # 退出
from flask import flash  # 消息闪现
from flask import request
from flask import session
from flask import url_for  # url生成器

import os
from app import db
from app import app
from app.models import Tag
from app.models import User
from app.models import Movie
from app.models import UserLog
from app.models import Comment
from app.models import MovieCol
from app.models import PreView

from app.home.forms import RegisterForm  # 导入注册表单验证
from app.home.forms import LoginForm  # 登陆表单验证
from app.home.forms import UserForm  # 导入会员中心的表单验证
from app.home.forms import PwdForm  # 修改密码表单验证
from app.home.forms import CommentForms  # 评论验证表单

from werkzeug.security import generate_password_hash  # 导入加密工具
from app.home.decorator import user_login_req  # 登陆验证装饰器
from app.admin.updata import change_filename  # 导入修改上传头像的名称


@home.route("/<int:page>", methods=["GET"])
def index(page=1):
    tid = request.args.get("tid", 0)  # 标签
    star = request.args.get("star", 0)  # 星级
    time = request.args.get("time", 0)  # 上映时间
    pm = request.args.get("pm", 0)  # 播放数量
    cm = request.args.get("cm", 0)  # 评论数量
    tages = Tag.query.all()  # 获取所有的标签
    movie = Movie.query
    p = dict(
        tid=tid,
        star=star,
        time=time,
        pm=pm,
        cm=cm
    )
    datanum = {k: int(v) for k, v in p.items() if int(v) > 0}
    if datanum.get('tid'):
        movie = movie.filter_by(tag_id=datanum.get('tid'))
    if datanum.get('star'):
        movie = movie.filter_by(star=datanum.get('star'))
    if datanum.get('time'):
        if datanum.get('time') == 1:
            movie = movie.order_by(Movie.addtime.desc())
        if datanum.get('time') == 2:
            movie = movie.order_by(Movie.addtime.asc())

    if datanum.get('pm'):
        if datanum.get('pm') == 1:
            movie = movie.order_by(Movie.playnum.desc())
        if datanum.get('pm') == 2:
            movie = movie.order_by(Movie.playnum.asc())

    if datanum.get('cm'):
        if datanum.get('cm') == 1:
            movie = movie.order_by(Movie.commentnum.desc())
        if datanum.get('cm') == 2:
            movie = movie.order_by(Movie.commentnum.asc())
    page_data = movie.paginate(page=int(page), per_page=10)
    return render_template("home/index.html", tages=tages, p=p, page_data=page_data)


# 电影播放
@home.route("/play/<int:id>", methods=["GET", "POST"])
@user_login_req
def play(id=None):
    if id is not None:
        form = CommentForms()
        play_movie = Movie.query.filter_by(id=int(id)).first()
        if play_movie is None:
            return redirect(url_for('home.index', page=1))
        # 播放数量加一
        play_movie.playnum += 1
        db.session.add(play_movie)
        db.session.commit()
        # 获取当前电影的评论-==
        commit = Comment.query.filter_by(movie_id=id).order_by(Comment.addtime.desc())
        # 添加评论
        if request.method == "POST":
            if form.validate_on_submit():
                data = form.data
                comment = Comment(
                    content=data.get('content'),
                    movie_id=id,
                    user_id=session['user_id']
                )
                db.session.add(comment)
                db.session.commit()
                return redirect(url_for('home.play', id=id))
    return render_template("home/play.html", play_movie=play_movie, commit=commit, form=form)


# 电影的收藏
@home.route("/playcol/", methods=["GET"])
@user_login_req
def playcol():
    id = request.args.get('id', None)
    if id is not None:
        # 查询电影是否已经收藏，如果已经收藏就取消收藏，如果没有收藏就加入收藏
        moviecol = MovieCol.query.filter_by(id=id).first()
        print(moviecol)
        if moviecol is None:
            moviecol = MovieCol(
                movie_id=id,
                user_id=session["user_id"]
            )
            db.session.add(moviecol)
            db.session.commit()
            flash("收藏成功")
        else:
            db.session.delete(moviecol)
            db.session.commit()
            flash("取消收藏成功")
    return redirect(url_for('home.play', id=id))


# 电影搜索
@home.route("/search/<int:page>", methods=["GET"])
def search(page=1):
    key = request.args.get("key", None)
    if key is None:
        key = session.get('key')
    else:
        session['key'] = key
    page_data = Movie.query.filter(Movie.title.ilike("%" + key + "%")).order_by(Movie.addtime.desc())
    page_data = page_data.paginate(page=page, per_page=10)
    search_num = len(page_data.items)
    return render_template("home/search.html", page_data=page_data, key=key, search_num=search_num)


# 登陆
@home.route("/login/", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(email=data["email"]).first()
        if not user.check_pwd(data["pwd"]):
            flash("密码错误")
            return redirect(url_for("home.login"))
        # 账号密码正确
        session["user"] = data["email"]
        session["user_id"] = user.id
        userlog = UserLog(
            user_id=user.id,
            ip=request.remote_addr
        )
        db.session.add(userlog)
        db.session.commit()
        return redirect(url_for("home.user"))
    return render_template("home/login.html", form=form)


# 退出
@home.route("/logout/")
@user_login_req
def logout():
    session.pop('user', None)
    session.pop('user_id', None)
    return redirect(url_for("home.login"))


# 注册
@home.route("/register/", methods=["GET", "POST"])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        data = form.data
        user = User(
            name=data.get('name'),
            email=data.get('email'),
            phone=data.get('phone'),
            pwd=generate_password_hash(data.get('pwd')),
            info="他很懒，什么也没有填写！"
        )
        db.session.add(user)
        db.session.commit()
        flash("注册成功")
        # 进行登陆并且保存session
        session["user"] = data.get('email')
        session["user_id"] = user.id
        return redirect(url_for('home.user'))
    return render_template("home/register.html", form=form)


# 会员中心
@home.route("/user/", methods=["GET", "POST"])
@user_login_req
def user():
    form = UserForm()
    user = User.query.get_or_404(session["user_id"])
    if request.method == "GET":
        form.info.data = user.info
    if form.validate_on_submit():
        data = form.data
        # 获取到头像文件
        face_name = form.face.data.filename
        # 判断文件夹是否存在，如果不存在就创建
        if not os.path.exists(app.config['UP_DIR'] + "/user/"):
            os.mkdir(app.config["UP_DIR"] + "/user/")
        # 对头像文件进行重命名
        face = change_filename(face_name)
        # 保存头像到本地文件
        form.face.data.save(app.config["UP_DIR"] + "/user/" + face)
        # 进行修改入库操作
        user.name = data.get('name')
        user.email = data.get('email')
        user.phone = data.get('phone')
        user.face = face
        user.info = data.get('info')
        db.session.add(user)
        db.session.commit()
        flash("资料修改成功")
        return redirect(url_for('home.user'))
    return render_template("home/user.html", form=form, user=user)


# 修改密码
@home.route("/pwd/", methods=["GET", "POST"])
@user_login_req
def pwd():
    form = PwdForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(email=session.get('user')).first()
        user.pwd = generate_password_hash(data.get('newpwd'))
        db.session.add(user)
        db.session.commit()
        flash("密码修改成功, 请重新登录!")
        return redirect(url_for('home.logout'))
    return render_template("home/pwd.html", form=form)


# 评论列表
@home.route("/comments/<int:page>", methods=["GET"])
@user_login_req
def comments(page=1):
    data_page = Comment.query.filter_by(user_id=session.get('user_id')).order_by(Comment.addtime.desc()).paginate(
        page=page, per_page=10)
    return render_template("home/comments.html", data_page=data_page)


# 登陆日志
@home.route("/loginlog/", methods=["GET"])
@user_login_req
def loginlog():
    data_page = UserLog.query.filter_by(user_id=session.get('user_id')).order_by(UserLog.add_time.desc())[:10]
    return render_template("home/loginlog.html", data_page=data_page)


# 获取用户收藏的电影
@home.route("/moviecol/<int:page>", methods=["GET"])
@user_login_req
def moviecol(page=1):
    data_page = MovieCol.query.filter_by(user_id=session.get('user_id')).order_by(MovieCol.addtime.desc()).paginate(
        page=page, per_page=1)
    return render_template("home/moviecol.html", data_page=data_page)


@home.route("/animation/")
def animation():
    preview_data = PreView.query.all()
    return render_template("home/animation.html", data=preview_data)

app/templates/home/animation.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>热映电影</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='animation/css/style.css')}}">
</head>
<body>
<!--轮播图 开始 -->
<div class="main_banner">
    <div class="main_banner_wrap">
        <canvas id="myCanvas" width="150" height="150"></canvas>
        <div class="main_banner_box" id="m_box">
            <a href="javascript:void(0)" class="banner_btn js_pre">
                <span class="banner_btn_arrow"><i></i></span>
            </a>
            <a href="javascript:void(0)" class="banner_btn btn_next js_next">
                <span class="banner_btn_arrow"><i></i></span>
            </a>
            <ul>
                {% for v in data %}
                <li id="imgCard{{v.id-1}}">
                    <a href=""><span style="opacity:0;"></span></a>
                    <img src="{{ url_for('static', filename='uploads/'+v.logo)}}" alt="">
                    <p style="bottom:0">{{v.title}}</p>
                </li>
                {% endfor %}
            </ul>
            <!--火狐倒影图层-->
            <p id="rflt"></p>
            <!--火狐倒影图层-->
        </div>
        <!--序列号按钮-->
        <div class="btn_list">
        </div>
    </div>

</div>
<!--轮播图 结束 -->

<script type="text/javascript" src="{{ url_for('static', filename='animation/js/jquery.js')}}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='animation/js/script.js')}}"></script>

</body>
</html>

app/templates/home/comments.html
{% extends "home/home.html" %}
{% import 'ui/user_page.html' as pages %}
{% block css %}
<style>
    .navbar-brand > img {
        display: inline;
    }

    .col-lg-1, .col-lg-10, .col-lg-11, .col-lg-12, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-md-1, .col-md-10, .col-md-11, .col-md-12, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-sm-1, .col-sm-10, .col-sm-11, .col-sm-12, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-xs-1, .col-xs-10, .col-xs-11, .col-xs-12, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6, .col-xs-7, .col-xs-8, .col-xs-9 {
        padding-right: 3px;
        padding-left: 3px;
    }

    .media {
        padding: 3px;
        border: 1px solid #ccc
    }
</style>
{% endblock %}
{% block content %}
{% include "home/menu.html" %}
<div class="col-md-9">
    <div class="panel panel-warning">
        <div class="panel-heading">
            <h3 class="panel-title"><span class="glyphicon glyphicon-map-marker"></span>&nbsp;评论记录</h3>
        </div>
        <div class="panel-body">
            <ul class="commentList">
                {% for v in data_page.items %}
                <li class="item cl">
                    <a href="user.html">

                        {% if v.user.face %}
                        <i class="avatar size-L radius">
                            <img style="width: 50px;height: 50px;" alt="50x50"
                                 src="{{url_for('static', filename='uploads/user/'+v.user.face)}}"
                                 class="img-circle" style="border:1px solid #abcdef;">
                        </i>
                        {% endif %}
                    </a>
                    <div class="comment-main">
                        <header class="comment-header">
                            <div class="comment-meta">
                                <a class="comment-author" href="{{url_for('home.user')}}">{{v.user.name}}</a>
                                评论于
                                <time title="{{v.addtime}}" datetime="{{v.addtime}}">{{v.addtime}}
                                </time>
                            </div>
                        </header>
                        <div class="comment-body">
                            <p>{{v.content|safe}}</p>
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <div class="col-md-12 text-center">
                <nav aria-label="Page navigation">
                    {{pages.page(data_page, 'home.comments')}}
                </nav>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
<script>
    $(document).ready(function () {
        $("#m-3").addClass("active")
    })
</script>
{% endblock %}

app/templates/home/home.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{url_for('static', filename='/base/images/logo.png')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='base/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='base/css/bootstrap-movie.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='base/css/animate.css')}}">
    <style>
        .navbar-brand > img {
            display: inline;
        }

    </style>
    <style>
        .media {
            padding: 3px;
            border: 1px solid #ccc
        }

    </style>
    {% block css %}

    {% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{url_for('home.index', page=1)}}" class="navbar-brand" style="width:250px;">
                <img src="{{url_for('static', filename='base/images/logo.png')}}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！" id="key_movie">
                    <span class="input-group-btn">
                        <a class="btn btn-default" id="do_search"><span
                                class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{url_for('home.index', page=1)}}"><span
                            class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                <li>
                    {% if session['user'] %}
                    {% else %}
                    <a class="curlink" href="{{url_for('home.login')}}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                    {% endif %}
                </li>
                <li>
                    {% if session['user'] %}
                    {% else %}
                    <a class="curlink" href="{{url_for('home.register')}}"><span
                            class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                    {% endif %}
                </li>
                <li>
                    {% if session['user'] %}
                    <a class="curlink" href="{{url_for('home.logout')}}"><span
                            class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                    {% endif %}
                </li>
                <li>
                    {% if session['user'] %}
                    <a class="curlink" href="{{ url_for('home.user') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                    {% endif %}
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
<div class="container" style="margin-top:76px">
    {% block content %}{% endblock %}
</div>
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2017&nbsp;flaskmovie.imooc.com&nbsp;京ICP备 13046642号-2
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{url_for('static', filename='base/js/jquery.min.js')}}"></script>
<script src="{{url_for('static', filename='base/js/bootstrap.min.js')}}"></script>
<script src="{{url_for('static', filename='base/js/jquery.singlePageNav.min.js')}}"></script>
<script src="{{url_for('static', filename='base/js/wow.min.js')}}"></script>
<script src="{{url_for('static', filename='lazyload/jquery.lazyload.min.js')}}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
{% block js %}
{% endblock %}
<script>
    $(function () {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function () {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
        $("#do_search").click(function () {
            var key = $("#key_movie").val()
            location.href = "{{url_for('home.search', page=1)}}?key=" + key;
        })
    });

</script>
</body>
</html>

app/templates/home/index.html
{% extends "./home/home.html" %}
{% import 'ui/user_page.html' as pag %}
{% block content %}
<!--热门电影-->
<section id="hotmovie" style="margin-top:76px">
    <div class="container">
        <div class="row wow fadeInRight" data-wow-delay="0.6s">
            <div class="row">
                <iframe class="wow fadeIn" width="100%" height="375px" frameborder=0 scrolling=no
                        src="{{url_for('home.animation')}}"></iframe>
            </div>
        </div>
    </div>
</section>
<!--热门电影-->
<!--电影列表-->
<section id="movielist">
    <div class="container">
        <div class="row wow fadeIn" data-wow-delay="0.6s">
            <div class="col-md-12 table-responsive">
                <table class="table text-left table-bordered" id="movietags">
                    <tr>
                        <td style="width:10%;">电影标签</td>
                        <td style="width:90%;">
                            <a class="label label-info"
                               href="{{url_for('home.index', page=1)}}?tid=0&star={{p['star']}}&time={{p['time']}}&pm={{p['pm']}}&cm={{p['cm']}}"><span
                                    class="glyphicon glyphicon-tag"></span>全部</a>
                            {% for v in tages %}
                            <a class="label label-info"
                               href="{{url_for('home.index', page=1)}}?tid={{v.id}}&star={{p['star']}}&time={{p['time']}}&pm={{p['pm']}}&cm={{p['cm']}}"><span
                                    class="glyphicon glyphicon-tag"></span>&nbsp{{v.name}}</a>
                            {% endfor %}
                    </tr>
                    <tr>
                        <td>电影星级</td>
                        <td>
                            <a class="label label-warning"
                               href="{{url_for('home.index', page=1)}}?tid={{p['tid']}}&star=0&time={{p['time']}}&pm={{p['pm']}}&cm={{p['cm']}}"><span
                                    class="glyphicon glyphicon-star"></span>&nbsp;全部</a>
                            {% for v in range(1, 6) %}
                            <a class="label label-warning"
                               href="{{url_for('home.index', page=1)}}?tid={{p['tid']}}&star={{v}}&time={{p['time']}}&pm={{p['pm']}}&cm={{p['cm']}}"><span
                                    class="glyphicon glyphicon-star"></span>&nbsp;{{v}}星</a>
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <td>上映时间</td>
                        <td>
                            <a href="{{url_for('home.index', page=1)}}?tid={{p['tid']}}&star={{p['star']}}&time=1&pm={{p['pm']}}&cm={{p['cm']}}"
                               class="label label-default"><span class="glyphicon glyphicon-time">最近</span>
                            </a>
                            <a href="{{url_for('home.index', page=1)}}?tid={{p['tid']}}&star={{p['star']}}&time=2&pm={{p['pm']}}&cm={{p['cm']}}"
                               class="label label-default"><span class="glyphicon glyphicon-time">更早</span>
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td>播放数量</td>
                        <td>
                            <a href="{{url_for('home.index', page=1)}}?tid={{p['tid']}}&star={{p['star']}}&time={{p['time']}}&pm=1&cm={{p['cm']}}"
                               class="label label-success"><span class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底</span>
                            </a>
                            &nbsp;
                            <a href="{{url_for('home.index', page=1)}}?tid={{p['tid']}}&star={{p['star']}}&time={{p['time']}}&pm=2&cm={{p['cm']}}"
                               class="label label-danger"><span
                                    class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高</span></a>
                        </td>
                    </tr>
                    <tr>
                        <td>评论数量</td>
                        <td>
                            <a href="{{url_for('home.index', page=1)}}?tid={{p['tid']}}&star={{p['star']}}&time={{p['time']}}&pm={{p['pm']}}&cm=1"
                               class="label label-success"><span class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底</span>
                            </a>
                            &nbsp;
                            <a href="{{url_for('home.index', page=1)}}?tid={{p['tid']}}&star={{p['star']}}&time={{p['time']}}&pm={{p['pm']}}&cm=2"
                               class="label label-danger"><span
                                    class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高</span></a>
                        </td>
                    </tr>
                </table>
            </div>
            {% for i in page_data.items %}
            <div class="col-md-3">
                <div class="movielist text-center">
                    <img width="90px" height="50px" src="{{url_for('static', filename='uploads/'+i.logo)}}"
                         class="img-responsive center-block" alt="">
                    <div class="text-left" style="margin-left:auto;margin-right:auto;width:210px;">
                        <span style="color:#999;font-style: italic;">{{i.title}}</span><br>
                        <div>
                            {% for v in range(0, i.star) %}
                            <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                            {% endfor %}
                            {% for v in range(0, 5-i.star) %}
                            <span class="glyphicon glyphicon-star-empty" style="color:#FFD119"></span>
                            {% endfor %}
                        </div>
                    </div>
                    <a href="{{ url_for('home.play', id=i.id) }}" class="btn btn-primary" target="_blank" role="button"><span
                            class="glyphicon glyphicon-play"></span>&nbsp;播放</a>
                </div>
            </div>
            {% endfor %}
            <div class="col-md-12">
                <nav aria-label="Page navigation">
                    {{pag.page(page_data, 'home.index')}}
                </nav>
            </div>
        </div>
    </div>
</section>
<!--电影列表-->
{% endblock %}

app/templates/home/login.html
{% extends "home/home.html" %}
{% block content %}
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-log-in"></span>&nbsp;会员登录</h3>
            </div>
            <div class="panel-body">
                {% for msg in get_flashed_messages() %}
                <p class="login-box-msg" style="color: red;">{{ msg }}</p>
                {% endfor %}
                <form role="form" method="post" novalidate>
                    <fieldset>
                        <div class="form-group">
                            <label for="input_contact"><span class="glyphicon glyphicon-user"></span>&nbsp;账号</label>
                            {% for err in form.email.errors %}
                            <label style="color: red;">{{err}}</label>
                            {% endfor %}
                            {{form.email}}
                        </div>
                        <div class="col-md-12" id="error_contact"></div>
                        <div class="form-group">
                            <label for="input_password"><span class="glyphicon glyphicon-lock"></span>&nbsp;密码</label>
                            {% for err in form.pwd.errors %}
                            <label style="color: red;">{{err}}</label>
                            {% endfor %}
                            {{form.pwd}}
                        </div>
                        <div class="col-md-12" id="error_password"></div>
                        {{form.csrf_token}}
                        {{form.submit}}
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/loginlog.html
{% extends "home/home.html" %}
{% block css %}
<style>
    .navbar-brand > img {
        display: inline;
    }

    .col-lg-1, .col-lg-10, .col-lg-11, .col-lg-12, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-md-1, .col-md-10, .col-md-11, .col-md-12, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-sm-1, .col-sm-10, .col-sm-11, .col-sm-12, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-xs-1, .col-xs-10, .col-xs-11, .col-xs-12, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6, .col-xs-7, .col-xs-8, .col-xs-9 {
        padding-right: 3px;
        padding-left: 3px;
    }

    .media {
        padding: 3px;
        border: 1px solid #ccc
    }
</style>
{% endblock %}
{% block content %}
{% include "home/menu.html" %}
<div class="col-md-9">
    <div class="panel panel-warning">
        <div class="panel-heading">
            <h3 class="panel-title"><span class="glyphicon glyphicon-map-marker"></span>&nbsp;登录日志</h3>
        </div>
        <div class="panel-body">
            <table class="table table-bordered">
                <tr>
                    <td style="width:10%">编号</td>
                    <td style="width:30%">登录时间</td>
                    <td style="width:30%">登录IP</td>
                </tr>
                {% for v in data_page %}
                <tr>
                    <td>{{v.id}}</td>
                    <td>{{v.add_time}}</td>
                    <td>{{v.ip}}</td>
                </tr>
                {% endfor %}

            </table>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
<script>
    $(document).ready(function () {
        $('#m-4').addClass("active")
    })
</script>
{% endblock %}

app/templates/home/menu.html
<div class="col-md-3">
    <div class="list-group">
        <a href="{{ url_for('home.user') }}" class="list-group-item" id="m-1">
            <span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
        </a>
        <a href="{{ url_for('home.pwd') }}" class="list-group-item" id="m-2">
            <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
        </a>
        <a href="{{ url_for('home.comments', page=1) }}" class="list-group-item" id="m-3">
            <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
        </a>
        <a href="{{ url_for('home.loginlog') }}" class="list-group-item" id="m-4">
            <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
        </a>
        <a href="{{ url_for('home.moviecol', page=1) }}" class="list-group-item" id="m-5">
            <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏电影
        </a>
    </div>
</div>